Repository wassimchakib/Car-Rental-Front-End, pull requests merged in 2023-04, with the labels that each got.

#17 Car Rental: Navbar
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/index.css
  src/images/icon.png
Labels: enhancement

#18 Car Rental: Add Car Page
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Dropdown/Dropdown.jsx
  src/components/Images/Images.jsx
  src/components/Input/Input.jsx
  src/components/Navbar/Navbar.jsx
  src/components/ui/FormErrors.jsx
  src/pages/AddCar/AddCar.jsx
  src/pages/AddCar/index.css
Labels: enhancement

#19 Create My Reservations Page
  src/App.css
  src/App.js
  src/components/Navbar/index.css
  src/components/my-reservations/CarCard.jsx
  src/components/my-reservations/MyReservations.css
  src/components/my-reservations/MyReservations.jsx
Labels: enhancement, Front End, Husniddin

#22 Car Rental : Authentication
  package-lock.json
  package.json
  public/favicon.ico
  src/App.css
  src/App.js
  src/components/AuthenticationForm/AuthenticationForm.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/index.css
  src/components/Spinner/Spinner.jsx
  src/components/Spinner/index.css
  src/components/ui/FormErrors.jsx
  src/pages/AddCar/AddCar.jsx
  src/pages/AddCar/index.css
  src/redux/authentication/authenticationSlice.js
  src/redux/registration/registrationSlice.js
  src/redux/store.js
  src/routing/ProtectedRoute.jsx
Labels: enhancement

#23 Car Rental: Reservation Redux store
  src/components/ReservationForm/ReservationForm.jsx
  src/components/delete-car/DeleteCarCard.jsx
  src/components/my-reservations/CarCard.jsx
  src/pages/AddCar/AddCar.jsx
  src/pages/delete-car/DeleteCar.jsx
  src/pages/my-reservation/MyReservations.jsx
  src/redux/car/carSlice.js
  src/redux/reservation/reservationSlice.js
  src/redux/store.js
Labels: enhancement

#33 Unit and Integrations tests for Car
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/__tests__/add_car/AddCar.test.js
  src/__tests__/booking/Reserve.test.js
  src/__tests__/car_details/carDetails.test.js
  src/__tests__/cars/cars.test.js
  src/__tests__/data/allCars.json
  src/__tests__/data/car.json
  src/__tests__/data/cars.json
  src/__tests__/delete_car/DeleteCar.test.js
  src/components/Dropdown/Dropdown.jsx
  src/components/ReservationForm/ReservationForm.jsx
  src/components/cars-components/CarCard.js
  src/components/cars-components/CarDetails.js
  src/components/cars-components/CarList.js
  src/components/cars-components/CarsList.css
  src/components/cars-components/ImageCarousel.js
  src/components/cars-components/cars.js
  src/components/delete-car/DeleteCarCard.jsx
  src/pages/Reserve/Reserve.jsx
  src/pages/my-reservation/MyReservations.css
  src/redux/car/carSlice.js
  tailwind.config.js
Labels: enhancement, Husniddin
